// SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

// Generate a tiny AppBuildInfo with the app version from the single source (root gradle.properties),
// so the wasm build reports the same version the Android build does. (BuildConfig is Android-only.)
val generateAppVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/appVersion")
    val versionValue = providers.gradleProperty("appVersionName").get()
    outputs.dir(outputDir)
    inputs.property("version", versionValue)
    doLast {
        val file = outputDir.get().file("AppBuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by :web build.gradle.kts — do not edit.
            |package io.github.rotundtapir.fivehundred.web
            |
            |internal object AppBuildInfo {
            |    const val VERSION: String = "$versionValue"
            |}
            |
            """.trimMargin(),
        )
    }
}

// The browser build: a Kotlin/Wasm executable around :shared's FiveHundredApp.
// `wasmJsBrowserDistribution` emits a static site (build/dist/wasmJs/productionExecutable)
// that GitHub Pages serves as-is; `wasmJsBrowserRun` serves it locally for development.
kotlin {
    wasmJs {
        browser {
            commonWebpackConfig {
                outputFileName = "fivehundred.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        wasmJsMain {
            kotlin.srcDir(generateAppVersion)
            dependencies {
                implementation(project(":shared"))
                implementation(libs.kotlinx.browser)
                // For configureWebResources { }: resource URLs must stay relative to the page.
                implementation(compose.components.resources)
            }
        }
    }
}

compose.resources {
    packageOfResClass = "io.github.rotundtapir.fivehundred.web.generated.resources"
    // Resources live only in wasmJsMain (the fallback font); without this the Res class is
    // only generated for modules with commonMain resources.
    generateResClass = always
}
